# Albert heijn credentials
username: your-username
password: your-password

# Calendar event settings
summary: sum
location: location
description: desc
timezone: tz

# Path to geckodriver.exe
geckopath: path