# [MANDATORY]
# Albert heijn credentials
username: your-username
password: your-password

# Path to phantomjs.exe
phantomjspath: path

# [OPTIONAL]
# Calendar event settings
summary: Werken
location: Albert Heijn
timezone: Europe/Amsterdam

# Show the browser (if true set geckopath)
showbrowser: False

# Path to geckodriver.exe
geckopath: path
