#!/usr/bin/env python


from datetime import datetime, timedelta
import pytz
import yaml
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from typing import Iterator, Any


DUTCHMONTHS = [
    'januari', 'februari', 'maart', 'april', 'mei', 'juni',
    'juli', 'augustus', 'september', 'oktober', 'november', 'december'
]
class Email:

    def __init__(self, mode:str = 'default')-> None:

        self.mode = mode
        if mode != 'default':
            return

        with open('settings.yaml') as s:
                settings = yaml.load(s, yaml.FullLoader)
        
        # Email credentials and SMTP server configuration
        self.from_email = str(settings['your_email'])
        self.to_email = str(settings['send_to_email'])
        self.password = str(settings['your_email_password'])
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
        self.timezone = pytz.timezone(settings['timezone'])

        


    def send_email(self, json: Iterator[dict[str, Any]]) -> None:

        if self.mode != 'default':
            return

        body = self.__generate_schedule_table__(json)
        subject = f"Rooster voor week {self.week_number}" # Generated by generate schedule table # TODO: clean up

        # Create a MIME object
        msg = MIMEMultipart()
        msg['From'] = self.from_email
        msg['To'] = self.to_email
        msg['Subject'] = subject

        # Attach the body with the msg instance
        msg.attach(MIMEText(body, 'html'))

        try:
            # Create an SMTP session
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()  # Secure the connection
            server.login(self.from_email, self.password)  # Login to the email account
            text = msg.as_string()  # Convert the MIME object to a string
            server.sendmail(self.from_email, self.to_email, text)  # Send the email
            print("Email sent successfully!")
        except Exception as e:
            print(f"Failed to send email: {e}")
        finally:
            server.quit()  # Terminate the SMTP session



    # Helper function to convert time string "H:M" to total minutes
    def time_string_to_minutes(self, time_str: str) -> int:
        if time_str:
            time_str = time_str.split('<')[0].strip()  # Remove HTML tags and extra characters            
            hours, minutes = map(int, time_str.split(':'))
            return hours * 60 + minutes
        return 0
    

        # Convert total break minutes to hours:minutes format
    def minutes_to_time_string(self, total_minutes: int) -> str:
        hours, minutes = divmod(total_minutes, 60)
        return f"{hours:02}:{minutes:02}"


    def __generate_schedule_table__(self, json: Iterator[dict[str, Any]]) -> str:
        print("Generating schedule table")

        # Get the current date
        current_date = datetime.now(self.timezone)

        # Calculate the start of the current week (Monday)
        current_week_start = current_date - timedelta(days=current_date.weekday())

        # Calculate the first Monday of the second week after the current one
        second_week_monday = current_week_start + timedelta(weeks=1)
        
        self.week_number = second_week_monday.isocalendar()[1] # need it in the subject

        # Calculate the end of the week (Sunday)
        end_of_week = (second_week_monday + timedelta(days=6)).replace(tzinfo = self.timezone)

        # Debug
        #print("The first Monday of the second week after the current one is:", second_week_monday.strftime("%Y-%m-%d"))
        #print("The end of that week is:", end_of_week.strftime("%Y-%m-%d"))
        # Calculate dates of the current week
        # Calculate how many days to the next Monday


        # Flag to check if any event has been added
        events_found = False

        descriptions = [""] * 7 
        durations = [0] * 7 
        schedule = [[] for _ in range(7)]  # List of lists for multiple events per day
        unpaid_breaks = [0] * 7  # List to accumulate unpaid break minutes for each day
        paid_breaks = [0] * 7  # List to accumulate paid break minutes for each day
        total_worked_minutes = 0


        # Add rows for all schedule entries matching the current day
        for event in json:
            events_found = True



            start_datetime = datetime.fromisoformat(event['start']['dateTime']).astimezone(self.timezone)
            end_datetime = datetime.fromisoformat(event['end']['dateTime']).astimezone(self.timezone)
            if(start_datetime > end_of_week): break

            #print(f"Event looks like: {event_time_str}")  # Debug info
        
            # Calculate the index for the day of the week
            day_of_week = (start_datetime.date() - second_week_monday.date()).days

            if 0 <= day_of_week < 7:
                

                duration_seconds = (end_datetime - start_datetime).total_seconds()
                duration_minutes = int(duration_seconds // 60)
                durations[day_of_week] += duration_minutes # Format duration as HH:MM
                total_worked_minutes += duration_minutes

                # Convert escaped newlines to HTML line breaks and remove the signature
                description = event['description'].replace('\n', '<br>').replace('Event gemaakt door albert-heijn-calender-sync', '')

                # Extract the team name
                start_pos = description.find("Team:")
                start_pos += len("Team:")
                end_pos = description.find(",", start_pos)
                team = description[start_pos:end_pos].strip()

                # Extract break times

                start_unpaid_pos = description.find("Pauze (Onbetaald): ")
                start_paid_pos = description.find("Pauze (Betaald): ")

                if start_unpaid_pos != -1:
                    end_unpaid_pos = description.find(',', start_unpaid_pos)
                    if end_unpaid_pos == -1:
                        end_unpaid_pos = len(description)
                    unpaid_time_str = description[start_unpaid_pos + len("Pauze (Onbetaald): "):end_unpaid_pos].strip()
                    unpaid_breaks[day_of_week] += self.time_string_to_minutes(unpaid_time_str)

                if start_paid_pos != -1:
                    end_paid_pos = description.find(',', start_paid_pos)
                    if end_paid_pos == -1:
                        end_paid_pos = len(description)
                    paid_time_str = description[start_paid_pos + len("Pauze (Betaald): "):end_paid_pos].strip()
                    paid_breaks[day_of_week] += self.time_string_to_minutes(paid_time_str)

                schedule[day_of_week].append(f"{start_datetime.strftime('%H:%M')} - {end_datetime.strftime('%H:%M')} {team}")

                # Accumulate descriptions
                descriptions[day_of_week] += description[:start_unpaid_pos].replace(description[start_paid_pos:], "") + "<br>"

        for i in range(7):
            total_worked_minutes -= (unpaid_breaks[i] + paid_breaks[i])
            unpaid_breaks[i] = self.minutes_to_time_string(unpaid_breaks[i])
            paid_breaks[i] = self.minutes_to_time_string(paid_breaks[i])
            durations[i] = self.minutes_to_time_string(durations[i])

        # Generate the formatted dates for the week in one line
        # Debug
        # dates = [
        #     (
        #         f"{(current_date - timedelta(days=(current_date.weekday() - i))).day} " + 
        #         f"{DUTCHMONTHS[(current_date - timedelta(days=(current_date.weekday() - i))).month - 1]} " +
        #         f"{ (current_date - timedelta(days=(second_week_monday.weekday() - i))).year}")
        #     for i in range(7)
        # ]


        # Generate the formatted dates for the week in one line
        dates = [
            f"{(second_week_monday + timedelta(days=i)).day} " + 
            f"{DUTCHMONTHS[(second_week_monday + timedelta(days=i)).month - 1]} " + 
            f"{ (second_week_monday + timedelta(days=i)).year}"
            for i in range(7)
        ]

        # Debug
        event_time_formatted = "12:12"
        description = "Event gemaakt door albert-heijn-calender-sync"

        # Basic styles
        styles = """
        <style type="text/css">
        .body-text {
            font-family: Arial, sans-serif;
        }
        </style>
        """


        # Header
        html = f"""
        Hi Jan,
        <br><br>
        Je nieuwe rooster voor week {self.week_number} is:
        <br><br>
        <!--[if mso]>
        {styles}
        <![endif]-->
        <table id="week-schedule" style='width: 100%; min-width:800px;' cellspacing='0'>
            <thead>
            <tr>
                <td class="body-text" style="
                    width: 95px;
                    background: transparent;
                    border-bottom-width: 0px;
                    text-align: right;
                    border-right: 1px solid #dedede;
                    padding: 6px;
                    vertical-align: top;">
                </td>
        """
        
        # Days of the week headers
        days = ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"]
        for day in days:
            html += f"""
                <td class="body-text" style="
                    border-right: 1px solid #dedede;
                    padding: 6px;
                    width: 118px;
                    vertical-align: top;">
                    {day}
                </td>
            """
        
        html += """
        </tr>
            <tr>
                <td class="body-text" style="
                    width: 95px;
                    background: transparent;
                    border-bottom-width: 0px;
                    text-align: right;
                    border-right: 1px solid #dedede;
                    padding: 6px;
                    vertical-align: top;">
                </td>"""
        
        # Dates
        for date in dates:
            html += f"""
                <td class="body-text" style="
                    border-right: 1px solid #dedede;
                    width: 118px;
                    vertical-align: top;
                    background: #f0f0f0;
                    padding: 3px 6px;">
                    {date}
                </td>
            """
        
        html += "</tr>\n</thead>\n<tbody>\n"
        
        # Schedule
        html += "<tr>\n"
        html += f"""
            <td class="body-text" style="
                width: 95px;
                background: transparent;
                border-bottom-width: 0px;
                text-align: right;
                border-right: 1px solid #dedede;
                padding: 6px;
                vertical-align: top;">
            </td>
        """
        for events in schedule:
            if events:
                html += f"""
                    <td class="body-text" style="
                            border-right: 1px solid #dedede;
                            width: 118px;
                            vertical-align: top;
                            padding: 6px;
                            border-bottom: 1px solid #dedede;">
                            """
                for event in events:
                    html += f"""
                            <div style="background-color: #ebffe4; border-top: 1px solid #fff; padding: 3px 6px;">
                                {event}
                            </div>
                        """
                    
                html += f"""
                    </td>
                            """
            else:
                html += """
                    <td class="body-text" style="
                        border-right: 1px solid #dedede;
                        width: 118px;
                        vertical-align: top;
                        padding: 6px;
                        border-bottom: 1px solid #dedede;">
                    </td>
                """
        html += "</tr>\n"
        
        # Footer (with example rows for "Pauze", "Productieve uren", etc.)
        footer_rows = [
            ("Pauze Onbetaald", unpaid_breaks),
            ("Pauze Betaald", paid_breaks),
            ("Productieve uren", durations),
            ("Toeslagen", [""] * 7), # maybe add toeslagen
            ("Opmerkingen", descriptions) 
            # maybe add verlof here
        ]
        
        html += "<tfoot>\n"
        for label, values in footer_rows:
            html += "<tr>\n"
            html += f"""
                <td class="body-text" style="
                    width: 95px;
                    background: transparent;
                    border-bottom-width: 0px;
                    text-align: right;
                    border-right: 1px solid #dedede;
                    padding: 6px;
                    vertical-align: top;">
                    {label}
                </td>
            """
            for value in values:
                html += f"""
                    <td class="body-text" style="
                        border-right: 1px solid #dedede;
                        width: 118px;
                        vertical-align: top;
                        padding: 6px;
                        border-bottom: 1px solid #dedede;">
                        {value}
                    </td>
                """
            html += "</tr>\n"
        
        html += "</tfoot>\n</table>\n<br/><br/>\n"

        html += f"""
                <div class=3D"body-text" style=3D"margin: 15px 0 0 100px; font-family: =
Arial, sans-serif;">
        Totaal week: {self.minutes_to_time_string(total_worked_minutes)}    </div>
        """
    

        # If no events were found, add a message to the HTML
        if not events_found:
            print("No schedule entries for this week")
            html += '''
                <tr>
                    <td colspan="4">No schedule entries for this week.</td>
                </tr>
            '''

        # Debug
        # with open("test.html", 'w') as file:
        #     file.write(html)
        # print("HTML saved to test.html")


        return html