# [MANDATORY]
# Albert heijn credentials
username: pnl
password: wachtwoord

# Path to phantomjs.exe
phantomjspath: path

# [OPTIONAL]
# Calendar event settings
summary: Werk
reminder: 1440
location: Albert Heijn
timezone: Europe/Amsterdam

# Show the browser (if true set geckopath)
showbrowser: True

# Path to geckodriver.exe
geckopath: /usr/local/bin/geckodriver
