# [MANDATORY]
# Albert heijn credentials
username: pnl
password: wachtwoord


# [OPTIONAL]
# Calendar event settings
summary: Werk
reminder: 1440
location: Albert Heijn
timezone: Europe/Amsterdam

# Show the browser
showbrowser: True

# Path to geckodriver.exe
geckopath: path/to/geckodriver
